[workspace]
members = [
  "ivy-core",
  "ivy-graphics",
  "ivy-input",
  "ivy-resources",
  "ivy-rendergraph",
  "ivy-stb",
  "ivy-ui",
  "ivy-vulkan",
  "ivy-pbr",

  "examples/sandbox",
  "examples/vulkan"
]
