[package]
name = "ivy"
version = "1.5.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Application and game framework for Rust"

[workspace]
members = [
  "ivy-core",
  "ivy-graphics",
  "ivy-input",
  "ivy-resources",
  "ivy-rendergraph",
  "ivy-image",
  "ivy-ui",
  "ivy-vulkan",
  "ivy-postprocessing",
  "ivy-physics",
  "ivy-random",
]

[dependencies]
ivy-core = { path = "./ivy-core" }
ivy-graphics = { path = "./ivy-graphics" }
ivy-input = { path = "./ivy-input" }
ivy-physics = { path = "./ivy-physics" }
ivy-postprocessing = { path = "./ivy-postprocessing" }
ivy-random = { path = "./ivy-random" }
ivy-rendergraph = { path = "./ivy-rendergraph" }
ivy-resources = { path = "./ivy-resources" }
ivy-image = { path = "./ivy-image" }
ivy-ui = { path = "./ivy-ui" }
ivy-vulkan = { path = "./ivy-vulkan" }

[dev-dependencies]
anyhow = "1.0.41"
atomic_refcell = "0.1.7"

flume = "0.10.7"
hecs = "0.5.2"
glfw = { version = "0.41.0", features = [ "vulkan" ] }
hecs-hierarchy = "0.1.8"
ultraviolet = "0.8.1"
log = "0.4.14"


[build-dependencies]
anyhow = "1.0.41"
