[package]
name = "ivy-engine"
version = "0.10.5"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2021"
description = "Application and game framework for Rust"

license-file = "./LICENSE"
keywords = ["graphics", "physics", "game-engine", "game", "vulkan"]
documentation = "https://lib.rs/ivy"
repository = "https://github.com/ten3roberts/ivy-engine"
readme = "./README.md"

[workspace]
members = [
  "ivy-base",
  "ivy-graphics",
  "ivy-input",
  "ivy-resources",
  "ivy-rendergraph",
  "ivy-image",
  "ivy-ui",
  "ivy-vulkan",
  "ivy-postprocessing",
  "ivy-physics",
  "ivy-collision",
  "ivy-random",
]

[workspace.dependencies]
anyhow = "1.0"
flume = "0.11"
tracing = "0.1"
tracing-tree = "0.3"
tracing-subscriber = "0.3"
palette = "0.7"
glam = { version = "0.20", features = ["bytemuck", "rand"] }
serde = { version = "1.0", features = ["derive"] }
rand_distr = "0.4"
rand = "0.8"
slotmap = "1.0"
atomic_refcell = "0.1"
smallvec = "1.0"
itertools = "0.12"
once_cell = "1.0"


parking_lot = "0.12"
thiserror = "1.0"
flax = { git = "https://github.com/ten3roberts/flax", features = [ "serde", "derive", "puffin" ] }


[dependencies]
ivy-collision = { path = "./ivy-collision", version = "0.10" }
ivy-base = { path = "./ivy-base", version = "0.10" }
ivy-graphics = { path = "./ivy-graphics", version = "0.10" }
ivy-image = { path = "./ivy-image", version = "0.10" }
ivy-input = { path = "./ivy-input", version = "0.10" }
ivy-physics = { path = "./ivy-physics", version = "0.10" }
ivy-postprocessing = { path = "./ivy-postprocessing", version = "0.10" }
ivy-random = { path = "./ivy-random", version = "0.10" }
ivy-rendergraph = { path = "./ivy-rendergraph", version = "0.10" }
ivy-resources = { path = "./ivy-resources", version = "0.10" }
ivy-ui = { path = "./ivy-ui", version = "0.10" }
ivy-vulkan = { path = "./ivy-vulkan", version = "0.10" }
ivy-presets = { path = "./ivy-presets", version = "0.10" }
ivy-window = { path = "./ivy-window", version = "0.10" }

derive_more = "0.99.17"
bytemuck = { version = "1.9.1", features = ["derive"] }
image = { version = "0.24.2", features = ["png", "jpeg"] }

[dev-dependencies]
anyhow = "1.0.57"
atomic_refcell = "0.1.8"

flume = "0.10.12"
parking_lot = "0.12.0"
slotmap = "1.0.6"
hecs = "0.7.6"
glfw = { version = "0.44.0", features = ["vulkan"] }
hecs-hierarchy = "0.11.6"
glam.workspace = true
log = "0.4.17"
color-eyre = "0.6.1"
tracing = "0.1.34"
tokio = { version = "1.18.2", features = ["full"] }
tracing-tree = "0.2.0"
tracing-subscriber = "0.3.11"
futures = "0.3.21"
winit = "0.26.1"
wgpu = "0.12.0"
thiserror = "1.0.31"

[features]
default = []
serialize = [
  "ivy-base/serialize",
  "ivy-ui/serialize",
  "ivy-physics/serialize",
  "ivy-vulkan/serialize",
  "ivy-resources/serialize",
  "ivy-graphics/serialize",
]

[profile.release]
debug = true
