[package]
name = "ivy"
version = "0.10.2"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Application and game framework for Rust"

license-file = "./LICENSE"
keywords = [ "graphics", "physics", "game engine", "game", "vulkan" ]
documentation = "https://lib.rs/ivy"
repository = "https://github.com/ten3roberts/ivy"
readme = "./README.md"

[workspace]
members = [
  "ivy-base",
  "ivy-graphics",
  "ivy-input",
  "ivy-resources",
  "ivy-rendergraph",
  "ivy-image",
  "ivy-ui",
  "ivy-vulkan",
  "ivy-postprocessing",
  "ivy-physics",
  "ivy-collision",
  "ivy-random",
]

[dependencies]
ivy-collision = { path = "./ivy-collision" }
ivy-templates = { path = "./ivy-templates" }
ivy-base = { path = "./ivy-base" }
ivy-graphics = { path = "./ivy-graphics" }
ivy-image = { path = "./ivy-image" }
ivy-input = { path = "./ivy-input" }
ivy-physics = { path = "./ivy-physics" }
ivy-postprocessing = { path = "./ivy-postprocessing" }
ivy-random = { path = "./ivy-random" }
ivy-rendergraph = { path = "./ivy-rendergraph" }
ivy-resources = { path = "./ivy-resources" }
ivy-ui = { path = "./ivy-ui" }
ivy-vulkan = { path = "./ivy-vulkan" }
ivy-presets = { path = "./ivy-presets", version = "0.10.0" }
ivy-window = { path = "./ivy-window", version = "0.10.0" }
hecs = "0.7.3"
hecs-schedule = "0.5.0"
derive_more = "0.99.17"

[dev-dependencies]
anyhow = "1.0.52"
atomic_refcell = "0.1.8"

flume = "0.10.10"
parking_lot = "0.11.2"
slotmap = "1.0.6"
hecs = "0.7.3"
glfw = { version = "0.43.0", features = [ "vulkan" ] }
hecs-hierarchy = "0.11.0"
glam = "0.20.2"
log = "0.4.14"

[features]
default = []
crossbeam-channel = ["ivy-base/crossbeam-channel"]
serialize = [
  "ivy-base/serialize",
  "ivy-ui/serialize",
  "ivy-physics/serialize",
  "ivy-vulkan/serialize",
  "ivy-resources/serialize",
  "ivy-templates/serialize",
  "ivy-graphics/serialize"
]

[profile.release]
debug = true
