[package]
name = "ivy-collision"
version = "0.9.0"
edition = "2018"
description = "3D collision crate for Ivy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
derive-for = "1.2.2"
derive_more = "0.99.17"
flume = "0.10.9"
hecs = "0.7.1"
hecs-schedule = "0.3.18"
ivy-base = { path = "../ivy-base", version = "0.9" }
ivy-resources = { path = "../ivy-resources", version = "0.9" }
palette = "0.6.0"
records = "0.1.1"
slotmap = "1.0.6"
smallvec = "1.7.0"
ultraviolet = "0.8.1"
