[package]
name = "ivy-ui"
version = "1.6.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "GUI library for Ivy"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
fontdue = "0.5.2"
hecs = "0.5"
hecs-hierarchy = "0.1"
ivy-graphics = { path = "../ivy-graphics", version = "*" }
ivy-image = { path = "../ivy-image", version = "1.4" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
ivy-vulkan = { path = "../ivy-vulkan", version = "*" }
thiserror = "1.0"
ultraviolet = "0.8"
