[package]
name = "ivy-ui"
version = "1.8.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "GUI library for Ivy"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
derive-for = "1.2.2"
derive_more = "0.99.16"
fontdue = "0.6.2"
hecs = "0.6.5"
hecs-hierarchy = "0.4.0"
ivy-base = { path = "../ivy-base", version = "1.4" }
ivy-graphics = { path = "../ivy-graphics", version = "1.7" }
ivy-image = { path = "../ivy-image", version = "1.4" }
ivy-rendergraph = { path = "../ivy-rendergraph", version = "1.7" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
ivy-vulkan = { path = "../ivy-vulkan", version = "1.7" }
thiserror = "1.0.30"
ultraviolet = { version = "0.8.1", features = [ "int" ] }
