[package]
name = "ivy-ui"
version = "0.9.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "GUI library for Ivy"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
derive-for = "1.2.2"
derive_more = "0.99.17"
fontdue = "0.6.2"
hecs = "0.7.1"
hecs-hierarchy = "0.8.0"
ivy-base = { path = "../ivy-base", version = "0.9" }
glfw = "0.43.0"
ivy-graphics = { path = "../ivy-graphics", version = "0.9" }
ivy-image = { path = "../ivy-image", version = "0.1" }
ivy-rendergraph = { path = "../ivy-rendergraph", version = "0.9" }
ivy-resources = { path = "../ivy-resources", version = "0.9" }
ivy-vulkan = { path = "../ivy-vulkan", version = "0.9" }
ivy-input = { path = "../ivy-input", version = "0.9" }
thiserror = "1.0.30"
ultraviolet = { version = "0.8.1", features = [ "int" ] }
flume = "0.10.9"
hecs-schedule = "0.3.18"
serde = { version = "1.0.131", features = [ "derive" ], optional = true }
records = "0.1.1"

[features]
default = []
serialize = [ "serde", "ultraviolet/serde" ]
