[package]
name = "ivy-graphics"
version = "1.7.1"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Provides high level graphics abstractions like Meshes, Materials, etc. Builds on top of ivy-vulkan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
anymap = "0.12.1"
ash = "0.33"
derive_more = "0.99"
glfw = "0.41"
gltf = "0.15"
hecs = "0.6"
ivy-core = { path = "../ivy-core", version = "1.7" }
ivy-image = { path = "../ivy-image", version = "1.1" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
ivy-vulkan = { path = "../ivy-vulkan", version = "1.7" }
parking_lot = "0.11"
rectangle-pack = "0.4"
smallvec = "1.6.1"
thiserror = "1.0"
ultraviolet = "0.8"
