[package]
name = "ivy-graphics"
version = "0.1.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Provides high level graphics abstractions like Meshes, Materials, etc. Builds on top of ivy-vulkan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
ash = "0.32"
derive_more = "0.99"
glfw = "0.41"
gltf = "0.15"
hecs = "0.5"
ivy-resources = { path = "../ivy-resources", version = "0.2" }
ivy-vulkan = { path = "../ivy-vulkan", version = "*" }
thiserror = "1.0"
ultraviolet = "0.8"
