[package]
name = "ivy-wgpu"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ivy-base = { path = "../ivy-base" }
ivy-assets = { path = "../ivy-assets" }

winit.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
glam.workspace = true
flax.workspace = true
anyhow.workspace = true
tracing.workspace = true
puffin.workspace = true
image.workspace = true
puffin_http.workspace = true
flume.workspace = true
itertools.workspace = true
futures.workspace = true
