[package]
name = "ivy-rendergraph"
version = "0.2.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hecs = "0.5"
itertools = "0.10"
ivy-graphics = { path = "../ivy-graphics", version = "*" }
ivy-resources = { path = "../ivy-resources", version = "0.2" }
ivy-vulkan = { path = "../ivy-vulkan", version = "*" }
slotmap = "1.0"
thiserror = "1.0"
