[package]
name = "ivy-rendergraph"
version = "1.9.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
hecs = "0.6.5"
itertools = "0.10.1"
ivy-base = { path = "../ivy-base", version = "1.7" }
ivy-graphics = { path = "../ivy-graphics", version = "1.7" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
ivy-vulkan = { path = "../ivy-vulkan", version = "1.7" }
slotmap = "1.0.6"
thiserror = "1.0.30"
