[package]
name = "ivy-rendergraph"
version = "1.7.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
hecs = "0.6"
itertools = "0.10"
ivy-graphics = { path = "../ivy-graphics", version = "1.7" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
ivy-vulkan = { path = "../ivy-vulkan", version = "1.7" }
slotmap = "1.0"
thiserror = "1.0"
