[package]
name = "ivy-rendergraph"
version = "0.9.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
hecs = "0.7.3"
itertools = "0.10.3"
ivy-base = { path = "../ivy-base", version = "0.9" }
ivy-graphics = { path = "../ivy-graphics", version = "0.9" }
ivy-resources = { path = "../ivy-resources", version = "0.9" }
ivy-vulkan = { path = "../ivy-vulkan", version = "0.9" }
slotmap = "1.0.6"
thiserror = "1.0.30"
