[package]
name = "ivy-input"
version = "1.8.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10.9"
glfw = { version = "0.42.0", features = [ "vulkan" ] }
ivy-base = { path = "../ivy-base", version = "1.8.0" }
ivy-graphics = { path = "../ivy-graphics", version = "1.8.0" }
ultraviolet = "0.8.1"
