[package]
name = "ivy-vulkan"
version = "0.10.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Low level vulkan abstractions for the Ivy game engine."

license-file = "../LICENSE"
keywords = [ "low-level", "graphics", "windowing", "game", "vulkan" ]
documentation = "https://lib.rs/ivy-vulkan"
repository = "https://github.com/ten3roberts/ivy"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.35.0"
glfw = { version = "0.43.0", features = [ "vulkan" ] }
gpu-allocator = "0.14.0"
ivy-image = { path = "../ivy-image", version = "0.10.0" }
ivy-resources = { path = "../ivy-resources", version = "0.10.0" }
ivy-base = { path = "../ivy-base", version = "0.10.0" }
log = "0.4.14"
parking_lot = "0.11.2"
smallvec = "1.7.0"
spirv-reflect = "0.2.3"
thiserror = "1.0.30"
glam = "0.20"
serde = { version = "1.0.132", features = [ "derive" ], optional = true }
bitflags = "1.3.2"
records = "0.1.1"

[features]
default = []
serialize = [ "serde", "glam/serde" ]
