[package]
name = "ivy-vulkan"
version = "0.3.1"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"
description = "Low level vulkan abstractions for the Ivy game engine."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5"
ash = "0.33"
glfw = { version = "0.41.0", features = [ "vulkan" ] }
ivy-stb = { path = "../ivy-stb", version = "0.1.0" }
log = "0.4"
parking_lot = "0.11"
smallvec = "1.6"
spirv-reflect = "0.2"
thiserror = "1.0"
ultraviolet = "0.8"
vk-mem = "0.2"
