[package]
name = "ivy-physics"
version = "1.4.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
hecs = "0.5"
ivy-core = { path = "../ivy-core", version = "1.7" }
thiserror = "1.0"
ultraviolet = "0.8"
