[package]
name = "ivy-physics"
version = "0.9.0"
edition = "2018"
description = "Provides physics for the Ivy framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
derive-for = "1.2.2"
derive_more = "0.99.17"
flume = "0.10.9"
hecs = "0.7.1"
ivy-collision = { path = "../ivy-collision", version = "0.9.0" }
ivy-base = { path = "../ivy-base", version = "0.9" }
ivy-random = { path = "../ivy-random", version = "0.9" }
ivy-graphics = { path = "../ivy-graphics", version = "0.9" }
ivy-resources = { path = "../ivy-resources", version = "0.9.0" }
smallvec = "1.7.0"
thiserror = "1.0.30"
ultraviolet = "0.8.1"
hecs-hierarchy = "0.8.0"
hecs-schedule = "0.3.18"
serde = { version = "1.0.131", features = [ "derive" ], optional = true }
records = "0.1.1"

[features]
default = []
serialize = [ "serde", "ultraviolet/serde" ]
