[package]
name = "ivy-physics"
version = "1.7.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
derive-for = "1.2.2"
derive_more = "0.99.16"
flume = "0.10.9"
hecs = "0.6.5"
ivy-collision = { path = "../ivy-collision", version = "0.1.0" }
ivy-core = { path = "../ivy-core", version = "1.7" }
ivy-graphics = { path = "../ivy-graphics", version = "*" }
ivy-resources = { path = "../ivy-resources", version = "1.4.0" }
smallvec = "1.7.0"
thiserror = "1.0.30"
ultraviolet = "0.8.1"
