[package]
name = "ivy-resources"
version = "0.9.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.8"
derive_more = "0.99.17"
hecs = "0.7.1"
hecs-schedule = "0.3.12"
parking_lot = "0.11.2"
slotmap = "1.0.6"
smallvec = "1.7.0"
thiserror = "1.0.30"
