[package]
name = "ivy-resources"
version = "1.9.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.8"
slotmap = "1.0.6"
parking_lot = "0.11.2"
thiserror = "1.0.30"
