[package]
name = "ivy-resources"
version = "1.7.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_refcell = "0.1.7"
slotmap = "1.0"
parking_lot = "0.11"
thiserror = "1.0"
