name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt install 
          libxi-dev
          libxcursor-dev
          libxinerama-dev
          libxrandr-dev
          libx11-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all

  check-licenses:
    name: "check licenses"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check licenses
          arguments: --all-features

  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
        - name: Install dependencies
          run: sudo apt install 
            libxi-dev
            libxcursor-dev
            libxinerama-dev
            libxrandr-dev
            libx11-dev
        - uses: dtolnay/rust-toolchain@nightly
        - uses: taiki-e/install-action@nextest
        - name: Run cargo test
          uses: actions-rs/cargo@v1
          with:
            command: nextest
            args: run --all-features
