[package]
name = "ivy-core"
version = "1.7.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
crossbeam-channel = { version = "0.5", optional = true }
derive_more = "0.99"
downcast-rs = "1.2"
flume = "0.10"
hecs = "0.5"
log = { version = "0.4", features = ["std"] }
thiserror = "1.0"
ultraviolet = "0.8"
