[package]
name = "ivy-core"
version = "0.1.0"
authors = ["Tim Roberts <ten3roberts@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = { version = "0.5", optional = true }
downcast-rs = "1.2"
flume = "0.10"
hecs = "0.5"
log = { version = "0.4", features = ["std"] }
